import { PrismaClient } from "@prisma/client";
import {
  aceh,
  sumatera_utara,
  sumatera_barat,
  riau,
  jambi,
  sumatera_selatan,
  bengkulu,
  lampung,
  kepulauan_bangka_belitung,
  kepulauan_riau,
  dki_jakarta,
  jawa_barat,
  jawa_tengah,
  jawa_timur,
  di_yogyakarta,
  bali,
  nusa_tenggara_barat,
  nusa_tenggara_timur,
  banten,
  kalimantan_barat,
  kalimantan_tengah,
  kalimantan_timur,
  kalimantan_selatan,
  kalimantan_utara,
  sulawesi_utara,
  sulawesi_tengah,
  sulawesi_selatan,
  sulawesi_tenggara,
  gorontalo,
  sulawesi_barat,
  maluku,
  maluku_utara,
  papua,
  papua_barat,
  papua_pegunungan,
  papua_selatan,
  papua_tengah,
  papua_barat_daya,
} from "./data/kabupaten";

export async function KabupatenSeeder(prisma: PrismaClient) {
  console.log("Seeding kabupaten...");

  await prisma.kabupaten.createMany({
    skipDuplicates: true,
    data: [
      ...aceh,
      ...sumatera_utara,
      ...sumatera_barat,
      ...riau,
      ...jambi,
      ...sumatera_selatan,
      ...bengkulu,
      ...lampung,
      ...kepulauan_bangka_belitung,
      ...kepulauan_riau,
      ...dki_jakarta,
      ...jawa_barat,
      ...jawa_tengah,
      ...jawa_timur,
      ...di_yogyakarta,
      ...bali,
      ...nusa_tenggara_barat,
      ...nusa_tenggara_timur,
      ...banten,
      ...kalimantan_barat,
      ...kalimantan_tengah,
      ...kalimantan_timur,
      ...kalimantan_selatan,
      ...kalimantan_utara,
      ...sulawesi_utara,
      ...sulawesi_tengah,
      ...sulawesi_selatan,
      ...sulawesi_tenggara,
      ...gorontalo,
      ...sulawesi_barat,
      ...maluku,
      ...maluku_utara,
      ...papua,
      ...papua_barat,
      ...papua_pegunungan,
      ...papua_selatan,
      ...papua_tengah,
      ...papua_barat_daya,
    ],
  });

  console.log("Kabupaten seeded successfully!");
}
